# Generated by Django 5.1.3 on 2024-11-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_moodentry_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10),
        ),
    ]
